### ISSUE TITLE
Pipelinerun fails enforce-stack-policy-post-build step using internal registry

### ISSUE THREAD

**Issue by bconey** [kabanero-io/kabanero-pipelines#378]
- Using Kabanero operator 0.9.0-rc.2, Kabanero pipelines 0.9.0-rc.3
- Stack hub setup using OCP internal registry
- Triggered pipelinerun for java-spring-boot2 app
- The enforce-stack-policy-pre-build was passed as seen below though it does show Null for DIGESTS and Cluster stack digest:  

  <img width="1268" alt="image" src="https://user-images.githubusercontent.com/31766760/81952511-92663a80-95d4-11ea-89fb-9094b3e42813.png">
- The build step was successful  
- The enforce-stack-post-build step failed with error  
`[ERROR] Failed stackPolicy enforcement, application image has already been built, but the stack configuration in .appsody-config.yaml became invalid during the build phase.`  

  <img width="1283" alt="image" src="https://user-images.githubusercontent.com/31766760/81952867-fb4db280-95d4-11ea-8f79-faff5eb369e7.png">
- There is an expectation that the failure should have occurred in the enforce-stack-policy-pre-build step if this error is related to being unable to read the digest from the stack when using activeDigest(or strictDigest).

**Comment by smcclem** [comment]
The issue here is that the Kabanero Operator was unable to access the internal secure registry during stack activation. This means the Operator cannot provide the "digest at activation" to the pipelines component when it needs it.  This means the pipeline component cannot properly determine the correct action.  

I've open an issue in the Kabanero Operator repo.  But I consider that issue the solution to this issue.  

https://github.com/kabanero-io/kabanero-operator/issues/715

**Comment by kaczyns** [comment]
I'm just curious why the pre-build check did not catch this.  It seems bad that the user had to wait until the build was finished to find out there was a problem.

I'm not trying to pass blame here - just wondering how we got this far.

**Comment by aadeshpa** [comment]
The decision on this issue is after the release cut rc.5 for pipelines, this issue can be worked on as stop ship of ICPA.

**Comment by kvijai82** [comment]
merged will be included in 0.9.1

**Comment by smcclem** [comment]
@kaczyns  To answer your question, the short answer is it was a bug.  The pre-build didn't validate the operator gave it an empty digest.  It didn't find a digest match, so according to the stackPolicy of activeDigest, it patched the version in the appsody-config file and allowed the pre-build to pass.    Post-build doesn't allow patching, so it went through the same process of not finding a match but the post-build failed because we can't allow patching at that point (since the build is already over).

**Comment by aadeshpa** [comment]
I see the fix for this is already merged in master PR: https://github.com/kabanero-io/kabanero-pipelines/pull/386

@mtamboli : please test it and then mark it as closed.

**Comment by bconey** [comment]
Verified.
